replace iso = "AF" if `1'=="Afghanistan"
replace iso = "AL" if `1'=="Albania"
replace iso = "DZ" if `1'=="Algeria"
replace iso = "AS" if `1'=="American Samoa"
replace iso = "AD" if `1'=="Andorra"
replace iso = "AO" if `1'=="Angola"
replace iso = "AI" if `1'=="Anguilla"
replace iso = "AQ" if `1'=="Antarctica"
replace iso = "AG" if `1'=="Antigua and Barbuda"
replace iso = "AG" if `1'=="Antigua And Barbuda"
replace iso = "AR" if `1'=="Argentina"
replace iso = "AM" if `1'=="Armenia"
replace iso = "AW" if `1'=="Aruba"
replace iso = "AU" if `1'=="Australia"
replace iso = "AT" if `1'=="Austria"
replace iso = "AZ" if `1'=="Azerbaijan"
replace iso = "BS" if `1'=="Bahamas, The"
replace iso = "BS" if `1'=="Bahamas"
replace iso = "BH" if `1'=="Bahrain"
replace iso = "BD" if `1'=="Bangladesh"
replace iso = "BB" if `1'=="Barbados"
replace iso = "BY" if `1'=="Belarus"
replace iso = "BE" if `1'=="Belgium"
replace iso = "BZ" if `1'=="Belize"
replace iso = "BJ" if `1'=="Benin"
replace iso = "BM" if `1'=="Bermuda"
replace iso = "BT" if `1'=="Bhutan"
replace iso = "BO" if `1'=="Bolivia"
replace iso = "BQ" if `1'=="Bonaire, Sint Eustatius and Saba"
replace iso = "BA" if `1'=="Bosnia and Herzegovina"
replace iso = "BA" if `1'=="Bosnia And Herzegovina"
replace iso = "BW" if `1'=="Botswana"
replace iso = "BV" if `1'=="Bouvet Island"
replace iso = "BR" if `1'=="Brazil"
replace iso = "IO" if `1'=="British Indian Ocean Territory"
replace iso = "BN" if `1'=="Brunei"
replace iso = "BN" if `1'=="Brunei Darussalam"
replace iso = "BG" if `1'=="Bulgaria"
replace iso = "BF" if `1'=="Burkina Faso"
replace iso = "BI" if `1'=="Burundi"
replace iso = "CV" if `1'=="Cabo Verde"
replace iso = "CV" if `1'=="Cape Verde"
replace iso = "KH" if `1'=="Cambodia"
replace iso = "CM" if `1'=="Cameroon"
replace iso = "CA" if `1'=="Canada"
replace iso = "KY" if `1'=="Cayman Islands"
replace iso = "KY" if `1'=="Caymen Islands"
replace iso = "CF" if `1'=="Central African Republic"
replace iso = "CF" if `1'=="Central Africa"
replace iso = "TD" if `1'=="Chad"
replace iso = "CL" if `1'=="Chile"
replace iso = "CN" if `1'=="China"
replace iso = "CX" if `1'=="Christmas Island"
replace iso = "CC" if `1'=="Cocos (Keeling) Islands (the)"
replace iso = "CO" if `1'=="Colombia"
replace iso = "KM" if `1'=="Comoros"
replace iso = "CD" if `1'=="Congo, Democratic Republic of"
replace iso = "CD" if `1'=="Congo, Democratic Republic Of"
replace iso = "CD" if `1'=="ZR"
replace iso = "CG" if `1'=="Congo, Republic of"
replace iso = "CG" if `1'=="Congo, Republic Of"
replace iso = "CK" if `1'=="Cook Islands"
replace iso = "CR" if `1'=="Costa Rica"
replace iso = "HR" if `1'=="Croatia"
replace iso = "CU" if `1'=="Cuba"
replace iso = "CW" if `1'=="Curaçao"
replace iso = "CY" if `1'=="Cyprus"
replace iso = "CZ" if `1'=="Czech Republic"
replace iso = "CI" if `1'=="Cote d'Ivoire"
replace iso = "CI" if `1'=="Cote D'Ivoire"
replace iso = "DK" if `1'=="Denmark"
replace iso = "DJ" if `1'=="Djibouti"
replace iso = "DM" if `1'=="Dominica"
replace iso = "DO" if `1'=="Dominican Republic"
replace iso = "EC" if `1'=="Ecuador"
replace iso = "EG" if `1'=="Egypt, Arab Republic of"
replace iso = "EG" if `1'=="Egypt, Arab Republic Of"
replace iso = "EG" if `1'=="Egypt"
replace iso = "SV" if `1'=="El Salvador"
replace iso = "GQ" if `1'=="Equatorial Guinea"
replace iso = "ER" if `1'=="Eritrea"
replace iso = "EE" if `1'=="Estonia"
replace iso = "SZ" if `1'=="Eswatini"
replace iso = "ET" if `1'=="Ethiopia"
replace iso = "FK" if `1'=="Falkland Islands (the) [Malvinas]"
replace iso = "FO" if `1'=="Faroe Islands (the)"
replace iso = "FJ" if `1'=="Fiji"
replace iso = "FI" if `1'=="Finland"
replace iso = "FR" if `1'=="France"
replace iso = "GF" if `1'=="French Guiana"
replace iso = "PF" if `1'=="French Polynesia"
replace iso = "TF" if `1'=="French Southern Territories (the)"
replace iso = "GA" if `1'=="Gabon"
replace iso = "GM" if `1'=="Gambia, The"
replace iso = "GE" if `1'=="Georgia"
replace iso = "DE" if `1'=="Germany"
replace iso = "GH" if `1'=="Ghana"
replace iso = "GI" if `1'=="Gibraltar"
replace iso = "GR" if `1'=="Greece"
replace iso = "GL" if `1'=="Greenland"
replace iso = "GD" if `1'=="Grenada"
replace iso = "GP" if `1'=="Guadeloupe"
replace iso = "GU" if `1'=="Guam"
replace iso = "GT" if `1'=="Guatemala"
replace iso = "GG" if `1'=="Guernsey"
replace iso = "GN" if `1'=="Guinea"
replace iso = "GW" if `1'=="Guinea-Bissau"
replace iso = "GY" if `1'=="Guyana"
replace iso = "HT" if `1'=="Haiti"
replace iso = "HM" if `1'=="Heard Island and McDonald Islands"
replace iso = "VA" if `1'=="Holy See (the)"
replace iso = "HN" if `1'=="Honduras"
replace iso = "HK" if `1'=="Hong Kong SAR, China"
replace iso = "HK" if `1'=="Hong Kong Sar, China"
replace iso = "HK" if `1'=="Hong Kong"
replace iso = "HU" if `1'=="Hungary"
replace iso = "IS" if `1'=="Iceland"
replace iso = "IN" if `1'=="India"
replace iso = "ID" if `1'=="Indonesia"
replace iso = "IR" if `1'=="Iran, Islamic Republic of"
replace iso = "IR" if `1'=="Iran, Islamic Republic Of"
replace iso = "IQ" if `1'=="Iraq"
replace iso = "IE" if `1'=="Ireland"
replace iso = "IM" if `1'=="Isle of Man"
replace iso = "IM" if `1'=="Isle Of Man"
replace iso = "IL" if `1'=="Israel"
replace iso = "IL" if `1'=="West Bank and Gaza"
replace iso = "IL" if `1'=="West Bank And Gaza"
replace iso = "IT" if `1'=="Italy"
replace iso = "JM" if `1'=="Jamaica"
replace iso = "JP" if `1'=="Japan"
replace iso = "JE" if `1'=="Jersey"
replace iso = "JO" if `1'=="Jordan"
replace iso = "KZ" if `1'=="Kazakhstan"
replace iso = "KE" if `1'=="Kenya"
replace iso = "KI" if `1'=="Kiribati"
replace iso = "KP" if `1'=="Korea, Democratic People's Republic of"
replace iso = "KP" if `1'=="Korea, Democratic People'S Republic Of"
replace iso = "KP" if `1'=="South Korea"
replace iso = "KR" if `1'=="Korea, Republic of"
replace iso = "KR" if `1'=="Korea, Republic Of"
replace iso = "1A" if `1'=="Kosovo"
replace iso = "KW" if `1'=="Kuwait"
replace iso = "KG" if `1'=="Kyrgyz Republic"
replace iso = "KG" if `1'=="Kyrgyzstan"
replace iso = "LA" if `1'=="Lao People's Democratic Republic"
replace iso = "LA" if `1'=="Lao People'S Democratic Republic"
replace iso = "LA" if `1'=="Lao"
replace iso = "LA" if `1'=="Laos"
replace iso = "LV" if `1'=="Latvia"
replace iso = "LB" if `1'=="Lebanon"
replace iso = "LS" if `1'=="Lesotho"
replace iso = "LR" if `1'=="Liberia"
replace iso = "LY" if `1'=="Libya"
replace iso = "LI" if `1'=="Liechtenstein"
replace iso = "LT" if `1'=="Lithuania"
replace iso = "LU" if `1'=="Luxembourg"
replace iso = "MO" if `1'=="Macao"
replace iso = "MG" if `1'=="Madagascar"
replace iso = "MW" if `1'=="Malawi"
replace iso = "MY" if `1'=="Malaysia"
replace iso = "MV" if `1'=="Maldives"
replace iso = "ML" if `1'=="Mali"
replace iso = "MT" if `1'=="Malta"
replace iso = "MH" if `1'=="Marshall Islands"
replace iso = "MQ" if `1'=="Martinique"
replace iso = "MR" if `1'=="Mauritania"
replace iso = "MU" if `1'=="Mauritius"
replace iso = "YT" if `1'=="Mayotte"
replace iso = "MX" if `1'=="Mexico"
replace iso = "FM" if `1'=="Micronesia, Federated States of"
replace iso = "FM" if `1'=="Micronesia, Federated States Of"
replace iso = "MD" if `1'=="Moldova"
replace iso = "MC" if `1'=="Monaco"
replace iso = "MN" if `1'=="Mongolia"
replace iso = "ME" if `1'=="Montenegro"
replace iso = "MS" if `1'=="Montserrat"
replace iso = "MA" if `1'=="Morocco"
replace iso = "MZ" if `1'=="Mozambique"
replace iso = "MM" if `1'=="Myanmar"
replace iso = "NA" if `1'=="Namibia"
replace iso = "NR" if `1'=="Nauru"
replace iso = "NP" if `1'=="Nepal"
replace iso = "NL" if `1'=="Netherlands"
replace iso = "NL" if `1'=="Netherlands Antilles [Netherlands]"
replace iso = "NC" if `1'=="New Caledonia"
replace iso = "NZ" if `1'=="New Zealand"
replace iso = "NI" if `1'=="Nicaragua"
replace iso = "NE" if `1'=="Niger"
replace iso = "NG" if `1'=="Nigeria"
replace iso = "NU" if `1'=="Niue"
replace iso = "NF" if `1'=="Norfolk Island"
replace iso = "MP" if `1'=="Northern Mariana Islands (the)"
replace iso = "NO" if `1'=="Norway"
replace iso = "OM" if `1'=="Oman"
replace iso = "PK" if `1'=="Pakistan"
replace iso = "PW" if `1'=="Palau"
replace iso = "PS" if `1'=="Palestine, State of"
replace iso = "PS" if `1'=="Palestinian Territory,Occupied"
replace iso = "PA" if `1'=="Panama"
replace iso = "PG" if `1'=="Papua New Guinea"
replace iso = "PY" if `1'=="Paraguay"
replace iso = "PE" if `1'=="Peru"
replace iso = "PH" if `1'=="Philippines"
replace iso = "PN" if `1'=="Pitcairn"
replace iso = "PL" if `1'=="Poland"
replace iso = "PT" if `1'=="Portugal"
replace iso = "PR" if `1'=="Puerto Rico"
replace iso = "QA" if `1'=="Qatar"
replace iso = "MK" if `1'=="Macedonia, former Yugoslav Republic of"
replace iso = "MK" if `1'=="Macedonia"
replace iso = "MK" if `1'=="Macedonia, Former Yugoslav Republic Of"
replace iso = "MK" if `1'=="Former Yugoslavia"
replace iso = "MK" if `1'=="North Macedonia"
replace iso = "RO" if `1'=="Romania"
replace iso = "RU" if `1'=="Russian Federation"
replace iso = "RU" if `1'=="Russia"
replace iso = "RW" if `1'=="Rwanda"
replace iso = "RE" if `1'=="Reunion"
replace iso = "BL" if `1'=="Saint Barthélemy"
replace iso = "SH" if `1'=="Saint Helena, Ascension and Tristan da Cunha"
replace iso = "KN" if `1'=="St. Kitts and Nevis"
replace iso = "KN" if `1'=="St. Kitts And Nevis"
replace iso = "LC" if `1'=="St. Lucia"
replace iso = "LC" if `1'=="Saint Lucia"
replace iso = "MF" if `1'=="Saint Martin (French part)"
replace iso = "PM" if `1'=="Saint Pierre and Miquelon"
replace iso = "VC" if `1'=="St. Vincent and the Grenadines"
replace iso = "VC" if `1'=="St. Vincent And The Grenadines"
replace iso = "WS" if `1'=="Samoa"
replace iso = "SM" if `1'=="San Marino"
replace iso = "ST" if `1'=="Sao Tome and Principe"
replace iso = "ST" if `1'=="Sao Tome And Principe"
replace iso = "SA" if `1'=="Saudi Arabia"
replace iso = "SN" if `1'=="Senegal"
replace iso = "RS" if `1'=="Serbia"
replace iso = "SC" if `1'=="Seychelles"
replace iso = "SL" if `1'=="Sierra Leone"
replace iso = "SG" if `1'=="Singapore"
replace iso = "SX" if `1'=="Sint Maarten (Dutch part)"
replace iso = "SX" if `1'=="St Maarten"
replace iso = "SK" if `1'=="Slovak Republic"
replace iso = "SK" if `1'=="Slovakia"
replace iso = "SI" if `1'=="Slovenia"
replace iso = "SB" if `1'=="Solomon Islands"
replace iso = "SO" if `1'=="Somalia"
replace iso = "ZA" if `1'=="South Africa"
replace iso = "GS" if `1'=="South Georgia and the South Sandwich Islands"
replace iso = "SS" if `1'=="South Sudan"
replace iso = "ES" if `1'=="Spain"
replace iso = "LK" if `1'=="Sri Lanka"
replace iso = "SD" if `1'=="Sudan"
replace iso = "SR" if `1'=="Suriname"
replace iso = "SJ" if `1'=="Svalbard and Jan Mayen"
replace iso = "SZ" if `1'=="Swaziland"
replace iso = "SE" if `1'=="Sweden"
replace iso = "CH" if `1'=="Switzerland"
replace iso = "SY" if `1'=="Syrian Arab Republic"
replace iso = "TW" if `1'=="Taiwan, China"
replace iso = "TJ" if `1'=="Tajikistan"
replace iso = "TZ" if `1'=="Tanzania"
replace iso = "TH" if `1'=="Thailand"
replace iso = "TL" if `1'=="Timor-Leste"
replace iso = "TL" if `1'=="East Timor"
replace iso = "TG" if `1'=="Togo"
replace iso = "TK" if `1'=="Tokelau"
replace iso = "TO" if `1'=="Tonga"
replace iso = "TT" if `1'=="Trinidad and Tobago"
replace iso = "TT" if `1'=="Trinidad And Tobago"
replace iso = "TN" if `1'=="Tunisia"
replace iso = "TR" if `1'=="Turkey"
replace iso = "TM" if `1'=="Turkmenistan"
replace iso = "TC" if `1'=="Turks and Caicos Islands (the)"
replace iso = "TV" if `1'=="Tuvalu"
replace iso = "UG" if `1'=="Uganda"
replace iso = "UA" if `1'=="Ukraine"
replace iso = "AE" if `1'=="United Arab Emirates"
replace iso = "GB" if `1'=="United Kingdom"
replace iso = "UM" if `1'=="United States Minor Outlying Islands"
replace iso = "US" if `1'=="United States"
replace iso = "UY" if `1'=="Uruguay"
replace iso = "UZ" if `1'=="Uzbekistan"
replace iso = "VU" if `1'=="Vanuatu"
replace iso = "VE" if `1'=="Venezuela, Republica Bolivariana de"
replace iso = "VE" if `1'=="Venezuela, Republica Bolivariana De"
replace iso = "VE" if `1'=="Venezuela"
replace iso = "VN" if `1'=="Vietnam"
replace iso = "VG" if `1'=="Virgin Islands, British"
replace iso = "VG" if `1'=="Virgin Islands (British)"
replace iso = "VI" if `1'=="Virgin Islands (U.S.)"
replace iso = "WF" if `1'=="Wallis and Futuna"
replace iso = "EH" if `1'=="Western Sahara"
replace iso = "YE" if `1'=="Yemen, Republic of"
replace iso = "YE" if `1'=="Yemen"
replace iso = "YE" if `1'=="Yemen, Republic Of"
replace iso = "ZM" if `1'=="Zambia"
replace iso = "ZW" if `1'=="Zimbabwe"
replace iso = "AX" if `1'=="Åland Islands"
replace iso = "US" if `1'=="United States of America"
replace iso = "IO" if `1'=="British lndian Ocean Territory"


